spring.application.name=IplPlayerService
 server.port=9091
 
 
 #Register with Eureka
 eureka.client.service-url.default-zone=http://localhost:8761
 #Link with config server
 spring.config.import=optional:configserver:
 
 #Enable all actuators
 management.endpoints.web.exposure.include=*
 management.endpoint.shutdown.access=unrestricted
 management.endpoint.health.show-details=always
 management.endpoint.env.access=unrestricted
 management.endpoint.env.show-values=always
 
 #info about app
 info.app.name=IplPlayerService
 info.app.id=4500
 info.app.size=10modules
 info.app.vendor=Natraj
 info.app.createdBy=Abhishek
 management.info.env.enabled=true
 
 #Connect to admin server as admin client
 spring.boot.admin.client.url=http://localhost:9999
 
 #Circuit breaker properties
 resilience4j.circuitbreaker.instances.IplPlayerService.slow-call-rate-threshold=60
 resilience4j.circuitbreaker.instances.IplPlayerService.failure-rate-threshold=50
 resilience4j.circuitbreaker.instances.IplPlayerService.minimum-number-of-calls=5
 resilience4j.circuitbreaker.instances.IplPlayerService.automatic-transition-from-open-to-half-open-enabled=true
 resilience4j.circuitbreaker.instances.IplPlayerService.wait-duration-in-open-state=10s
 resilience4j.circuitbreaker.instances.IplPlayerService.permitted-number-of-calls-in-half-open-state=3
 resilience4j.circuitbreaker.instances.IplPlayerService.sliding-window-size=10
 resilience4j.circuitbreaker.instances.IplPlayerService.sliding-window-type=COUNT_BASED
 resilience4j.circuitbreaker.instances.IplPlayerService.register-health-indicator=true 
 
 #logging
 logging.file.name=/SpringBootMS-Proj16-IplPlayerService-MiniProject/logging/ipl_player_service_elk_log1.txt
 logging.level.com.spring=DEBUG 
 
