spring.application.name=ConfigServer

server.port=8888

spring.cloud.config.server.git.uri=https://github.com/Abhisek-Git-01/Springboot-Config-Server-External-File.git

 #logging
 logging.file.name=/SpringBootMS-Proj16-IplPlayerService-MiniProject/logging/config_server_elk_log1.txt
 logging.level.com.spring=DEBUG 