spring.application.name=AdminServer

server.port=9999

 #logging
 logging.file.name=/SpringBootMS-Proj16-IplPlayerService-MiniProject/logging/admin_server_elk_log1.txt
 logging.level.com.spring=DEBUG 