spring.application.name=APIGateway

server.port=9898

spring.cloud.gateway.server.webmvc.routes[0].id=IPLPLAYERSERVICE
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:9091
spring.cloud.gateway.server.webmvc.routes[0].predicates[0].name=Path
spring.cloud.gateway.server.webmvc.routes[0].predicates[0].args.pattern=/player-api/**

spring.cloud.gateway.server.webmvc.routes[1].id=IPLTEAMSERVICE
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:9092
spring.cloud.gateway.server.webmvc.routes[1].predicates[0].name=Path
spring.cloud.gateway.server.webmvc.routes[1].predicates[0].args.pattern=/team-api/**